version: 0.2

env: 
  variables: 
    GO_VERSION: 1.16.5

phases:
  install:
    commands:
      - wget https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/go/bin:$PATH" && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
      - go get -v -u github.com/aws/aws-lambda-go
  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o build/bootstrap cmd/main.go
      # - zip myFunction.zip build/bootstrap
artifacts:
  files:
    - '**/*'
    # - myFunction.zip
  name: myFunction-$(date +%Y-%m-%d)